name: Tezster-CLI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.ref}}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

